### ISSUE TITLE
Determining highlight

### ISSUE THREAD

**Issue by kkhan01** [TomerShech/Binventor#2]
Determining highlight of keywords with an algorithm is cool, but there are often cases when languages are similar but their highlights are not. An example would be elisp. Here is a random snippet:
![image](https://user-images.githubusercontent.com/22206867/66081453-fbada780-e535-11e9-8910-843d2531677c.png)

The highlight should look more like this (ignoring the color scheme):
![image](https://user-images.githubusercontent.com/22206867/66081611-534c1300-e536-11e9-9963-e33184970112.png)

Many code pasting sites may mistaken it for a different language (although through talking we've determined you simply didn't have support). Either way, it would be wise to add an override by snippet name if the name has an extension (eg: `hello.el`, use elisp instead of trying to figure out the language).

**Comment by TomerShech** [comment]
Sounds clever mate. Thank you for your feedback and idea. I think I'll
implement it.

**Comment by TomerShech** [comment]
## Feature added!
now you can explicitly give your paste a name with the wanted extension (e.g. script.sh or program.lisp) and it will force [Highlight.js](https://highlightjs.org/) to highlight your code as the language extension.
